import { TradeProviderInfo } from "./trade-data.types";

export const TRADE_PROVIDERS: TradeProviderInfo[] = [
  {
    id: "us-census-api",
    name: "U.S. Census Bureau International Trade API",
    country: "United States",
    countryFlag: "🇺🇸",
    type: "aggregate",
    status: "connected",
    description: "Official U.S. government aggregate trade statistics by HS commodity code, origin/destination, and port of entry. Company names protected under 13 U.S.C. 301.",
    supportsCompanySearch: false,
    officialSourceUrl: "https://www.census.gov/foreign-trade/index.html",
  },
  {
    id: "us-sec-edgar",
    name: "U.S. SEC EDGAR Corporate Trade Filings",
    country: "United States",
    countryFlag: "🇺🇸",
    type: "company",
    status: "connected",
    description: "Official U.S. SEC public corporate disclosures detailing active international import/export operations, suppliers, and trade logistics.",
    supportsCompanySearch: true,
    officialSourceUrl: "https://www.sec.gov/edgar/searchedgar/companysearch",
  },
  {
    id: "uk-hmrc-importers",
    name: "UK HMRC Public Importers Directory",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    type: "company",
    status: "connected",
    description: "Official HM Revenue & Customs public dataset listing registered UK importing companies, registered addresses, and imported HS commodity codes.",
    supportsCompanySearch: true,
    officialSourceUrl: "https://www.gov.uk/government/organisations/hm-revenue-customs",
  },
  {
    id: "un-comtrade",
    name: "UN Comtrade International Trade Database",
    country: "Global (200+ Countries)",
    countryFlag: "🌐",
    type: "aggregate",
    status: "connected",
    description: "Official United Nations trade statistics covering international commodity flows, annual trade volumes, and net weights across 200+ reporting countries.",
    supportsCompanySearch: false,
    officialSourceUrl: "https://comtradeapi.un.org/",
  },
  {
    id: "us-trade-gov",
    name: "Trade.gov (U.S. International Trade Administration)",
    country: "United States",
    countryFlag: "🇺🇸",
    type: "aggregate",
    status: "setup-required",
    description: "U.S. ITA official trade leads, tariffs, and international procurement opportunities.",
    supportsCompanySearch: true,
    officialSourceUrl: "https://developer.trade.gov/",
    setupInstructions: {
      credentialsRequired: "Trade.gov API Key",
      registrationUrl: "https://developer.trade.gov/",
      envVarName: "TRADE_GOV_API_KEY",
    },
  },
  {
    id: "us-vessel-manifests",
    name: "U.S. Commercial Vessel Manifest Provider (ImportKey / Panjiva API)",
    country: "United States",
    countryFlag: "🇺🇸",
    type: "company",
    status: "setup-required",
    description: "U.S. Customs & Border Protection (CBP) daily sea freight bills of lading manifest data with detailed consignees and shippping records.",
    supportsCompanySearch: true,
    officialSourceUrl: "https://importkey.com/",
    setupInstructions: {
      credentialsRequired: "Commercial Manifest API Key / Subscription",
      registrationUrl: "https://importkey.com/api",
      envVarName: "IMPORTKEY_API_KEY",
    },
  },
  {
    id: "india-commerce-dept",
    name: "India Directorate General of Foreign Trade (DGFT)",
    country: "India",
    countryFlag: "🇮🇳",
    type: "aggregate",
    status: "setup-required",
    description: "Official Indian export/import trade data portal maintained by the Ministry of Commerce & Industry.",
    supportsCompanySearch: false,
    officialSourceUrl: "https://tradestat.commerce.gov.in/",
    setupInstructions: {
      credentialsRequired: "Data.gov.in API Key",
      registrationUrl: "https://data.gov.in/",
      envVarName: "DATA_GOV_IN_API_KEY",
    },
  },
  {
    id: "canada-statcan",
    name: "Statistics Canada Trade Data Online",
    country: "Canada",
    countryFlag: "🇨🇦",
    type: "aggregate",
    status: "setup-required",
    description: "Official Canadian international merchandise trade statistics portal.",
    supportsCompanySearch: false,
    officialSourceUrl: "https://www me.statcan.gc.ca/trade-commerce/",
    setupInstructions: {
      credentialsRequired: "StatCan Open Data API Key",
      registrationUrl: "https://www.statcan.gc.ca/",
      envVarName: "STATCAN_API_KEY",
    },
  },
];
